### ISSUE TITLE
Does not generate box

### ISSUE THREAD

**Issue by Panour** [paulh-rnd/TabbedBoxMaker#16]
InkscapeBug report (windows7 64 bit, pyton 2.7.5, langage french) :
Traceback (most recent call last):

  File "boxmaker.py", line 525, in <module>

    effect.affect()

  File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 215, in affect

    self.effect()

  File "boxmaker.py", line 257, in effect

    widthDoc  = self.unittouu(svg.get('width'))

AttributeError: BoxMaker instance has no attribute 'unittouu'

**Comment by applemuncy** [comment]
Please see closed issue #5

Old version of inkscape ?

**Comment by Panour** [comment]
switched from version 0.48 to 0.92, works fine!

**Comment by Panour** [comment]
Yes, I have updated and closed the issue, thank you for your help!
